### ISSUE TITLE
No site deployed at the address given

### ISSUE THREAD

**Issue by Zireael07** [lukeren314/poke-gans#42]
Title

**Comment by lukeren314** [comment]
Hi,
Sorry, but heroku shut down their free plan, and this project is so old I couldn't be bothered to redeploy it. Feel free to look at the code for inspiration (it's absolute garbage), though there are a million new techniques and frameworks to do the same thing but much better. Good luck!

**Comment by Zireael07** [comment]
Okay, I get it, but please edit the mention of heroku out of the README.
